title: <p align="center"> Banwari kumar </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/banwarisharma/">LinkedIn</a> |
  <a href="https://github.com/Banwarikumar">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Working in Oracle domain for 5 years.
  <br>
  </p>



theme: jekyll-theme-minimal
